In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

from sklearn.impute import SimpleImputer

#  to handle missing values

In [ ]:
# load the titanic dataset
# load dataset from github
df=pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# select and prepare Features
# select relevant columns
df_model = df[["Survived","Pclass","Sex","Age","Fare"  ]].copy()
#Convert 'sex' to numericc values
df_model["Sex"] =df_model["Sex"].map({"male": 0, "female":1})

In [10]:
df_model.head()

   Survived  Pclass  Sex   Age     Fare
0         0       3    0  22.0   7.2500
1         1       1    1  38.0  71.2833
2         1       3    1  26.0   7.9250
3         1       1    1  35.0  53.1000
4         0       3    0  35.0   8.0500

In [11]:
df_model.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
Fare          0
dtype: int64

In [12]:
df_model.shape

(891, 5)

In [13]:
# separate features (x) and target (y)
x= df_model.drop("Survived", axis=1)
y= df_model["Survived"]
x.head()

   Pclass  Sex   Age     Fare
0       3    0  22.0   7.2500
1       1    1  38.0  71.2833
2       3    1  26.0   7.9250
3       1    1  35.0  53.1000
4       3    0  35.0   8.0500

In [16]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [17]:
# Use SimpleImputer to  fill missing age with mean
imputer = SimpleImputer(strategy='mean')
x_imputed = imputer.fit_transform(x)
x_imputed[10]

array([ 3. ,  1. ,  4. , 16.7])

In [22]:
# Use SimpleImputer to fill missing Age with mean
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')  # Mean imputation for numerical columns

X_imputed = imputer.fit_transform(x)
x_imputed[:10]
# Use SimpleImputer to fill missing Age with mean

# Mean imputation for numerical columns

# What is SimpleImputer?

# SimpleImputer is a scikit-learn class that provides basic strategies for imputing missing values:

# It replaces missing values (NaN) with a specified strategy (mean, median, most frequent, or constant)

# In your case, you're using strategy='mean' which replaces missing Age values with the mean age

array([[ 3.        ,  0.        , 22.        ,  7.25      ],
       [ 1.        ,  1.        , 38.        , 71.2833    ],
       [ 3.        ,  1.        , 26.        ,  7.925     ],
       [ 1.        ,  1.        , 35.        , 53.1       ],
       [ 3.        ,  0.        , 35.        ,  8.05      ],
       [ 3.        ,  0.        , 29.69911765,  8.4583    ],
       [ 1.        ,  0.        , 54.        , 51.8625    ],
       [ 3.        ,  0.        ,  2.        , 21.075     ],
       [ 3.        ,  1.        , 27.        , 11.1333    ],
       [ 2.        ,  1.        , 14.        , 30.0708    ]])

In [27]:
# Now X_imputed is a NumPy array with no missing values

import numpy as np
np.isnan(X_imputed).any()

np.False_

In [30]:
# Step 6: Train Naive Bayes Classifier

# Initialize the classifier
from sklearn.naive_bayes import GaussianNB
nb_model = GaussianNB()

# Train on the training data
nb_model.fit(X_train, y_train)

GaussianNB()

In [32]:
from sklearn.model_selection import train_test_split

y = df_model["Survived"]
X_train, X_test, y_train, y_test = train_test_split(
    x_imputed, y, test_size=0.2, random_state=42
)

In [33]:
X_test

array([[  3.        ,   0.        ,  29.69911765,  15.2458    ],
       [  2.        ,   0.        ,  31.        ,  10.5       ],
       [  3.        ,   0.        ,  20.        ,   7.925     ],
       [  2.        ,   1.        ,   6.        ,  33.        ],
       [  3.        ,   1.        ,  14.        ,  11.2417    ],
       [  1.        ,   1.        ,  26.        ,  78.85      ],
       [  3.        ,   1.        ,  29.69911765,   7.75      ],
       [  3.        ,   0.        ,  16.        ,  18.        ],
       [  3.        ,   1.        ,  16.        ,   7.75      ],
       [  1.        ,   1.        ,  19.        ,  26.2833    ],
       [  1.        ,   0.        ,  37.        ,  53.1       ],
       [  3.        ,   0.        ,  44.        ,   8.05      ],
       [  3.        ,   1.        ,  29.69911765,  25.4667    ],
       [  3.        ,   0.        ,  30.        ,   7.225     ],
       [  2.        ,   0.        ,  36.        ,  13.        ],
       [  1.        ,   1.        ,  16.        ,  39.4       ],
       [  1.        ,   0.        ,  42.        ,  52.5542    ],
       [  3.        ,   1.        ,  29.69911765,   7.8292    ],
       [  2.        ,   0.        ,  27.        ,  13.        ],
       [  1.        ,   0.        ,  47.        ,  52.        ],
       [  3.        ,   0.        ,  24.        ,   7.8958    ],
       [  1.        ,   0.        ,  34.        ,  26.55      ],
       [  3.        ,   1.        ,  19.        ,   7.8542    ],
       [  3.        ,   0.        ,  20.        ,   9.225     ],
       [  3.        ,   0.        ,  29.69911765,  14.5       ],
       [  3.        ,   0.        ,  10.        ,  27.9       ],
       [  1.        ,   0.        ,  40.        ,  27.7208    ],
       [  2.        ,   0.        ,  31.        ,  13.        ],
       [  3.        ,   0.        ,   4.        ,  27.9       ],
       [  3.        ,   1.        ,  31.        ,   7.8542    ],
       [  3.        ,   0.        ,  19.        ,   7.8958    ],
       [  3.        ,   1.        ,  22.        ,   7.75      ],
       [  1.        ,   0.        ,  29.69911765,  30.6958    ],
       [  3.        ,   1.        ,  29.69911765,   7.55      ],
       [  3.        ,   0.        ,  18.        ,   8.05      ],
       [  3.        ,   0.        ,  27.        ,  14.4542    ],
       [  1.        ,   0.        ,  28.        ,  35.5       ],
       [  3.        ,   1.        ,  29.69911765,   7.75      ],
       [  1.        ,   1.        ,  30.        ,  31.        ],
       [  3.        ,   0.        ,  29.69911765,   7.8958    ],
       [  2.        ,   0.        ,  21.        ,  73.5       ],
       [  3.        ,   0.        ,  29.        ,   7.0458    ],
       [  3.        ,   0.        ,  29.69911765,   8.05      ],
       [  3.        ,   0.        ,  29.69911765,   7.75      ],
       [  3.        ,   1.        ,  45.        ,  14.4542    ],
       [  3.        ,   0.        ,  16.        ,  34.375     ],
       [  3.        ,   0.        ,  19.        ,   8.1583    ],
       [  3.        ,   0.        ,  23.        ,   9.225     ],
       [  3.        ,   0.        ,  24.        ,   7.05      ],
       [  1.        ,   0.        ,  58.        , 113.275     ],
       [  3.        ,   1.        ,   5.        ,  19.2583    ],
       [  1.        ,   1.        ,  52.        ,  93.5       ],
       [  3.        ,   0.        ,  40.        ,  27.9       ],
       [  1.        ,   0.        ,  11.        , 120.        ],
       [  3.        ,   0.        ,  65.        ,   7.75      ],
       [  1.        ,   1.        ,  18.        ,  79.65      ],
       [  2.        ,   0.        ,  32.        ,  10.5       ],
       [  1.        ,   1.        ,  50.        , 247.5208    ],
       [  2.        ,   1.        ,  35.        ,  21.        ],
       [  3.        ,   1.        ,  19.        ,   7.8792    ],
       [  3.        ,   0.        ,  21.        ,   7.775     ],
       [  2.        ,   1.        ,  13.        ,  19.5       ],
       [  2.        ,   1.        ,  28.        ,  26.        ],
       [  1.        ,   0.        ,  29.69911765,  25.925     ],
       [  3.        ,   0.        ,  29.69911765,   7.75      ],
       [  2.        ,   1.        ,  57.        ,  10.5       ],
       [  2.        ,   0.        ,  21.        ,  73.5       ],
       [  3.        ,   0.        ,  29.        ,   7.875     ],
       [  3.        ,   0.        ,  17.        ,   7.2292    ],
       [  1.        ,   1.        ,  52.        ,  78.2667    ],
       [  2.        ,   1.        ,  26.        ,  26.        ],
       [  1.        ,   1.        ,  18.        , 262.375     ],
       [  1.        ,   0.        ,  26.        ,  30.        ],
       [  1.        ,   1.        ,  39.        ,  83.1583    ],
       [  3.        ,   0.        ,  23.        ,   7.8542    ],
       [  3.        ,   0.        ,  36.        ,  15.55      ],
       [  3.        ,   1.        ,  30.5       ,   7.75      ],
       [  1.        ,   1.        ,  22.        ,  49.5       ],
       [  2.        ,   1.        ,  38.        ,  13.        ],
       [  3.        ,   1.        ,  41.        ,  20.2125    ],
       [  3.        ,   0.        ,  16.        ,  39.6875    ],
       [  2.        ,   1.        ,  29.        ,  10.5       ],
       [  1.        ,   1.        ,  40.        , 134.5       ],
       [  3.        ,   0.        ,  29.69911765,   7.7375    ],
       [  1.        ,   0.        ,  56.        ,  30.6958    ],
       [  1.        ,   0.        ,  71.        ,  49.5042    ],
       [  1.        ,   1.        ,  31.        , 113.275     ],
       [  1.        ,   1.        ,  30.        ,  56.9292    ],
       [  1.        ,   0.        ,  38.        ,   0.        ],
       [  3.        ,   0.        ,  29.69911765,   7.25      ],
       [  3.        ,   0.        ,   9.        ,  20.525     ],
       [  3.        ,   1.        ,   9.        ,  31.275     ],
       [  1.        ,   0.        ,  61.        ,  32.3208    ],
       [  3.        ,   0.        ,  29.69911765,   7.7292    ],
       [  3.        ,   0.        ,  29.69911765,   7.8958    ],
       [  3.        ,   0.        ,  28.        ,   7.8542    ],
       [  1.        ,   0.        ,  48.        ,  52.        ],
       [  3.        ,   0.        ,  45.        ,   8.05      ],
       [  2.        ,   1.        ,  36.        ,  13.        ],
       [  3.        ,   0.        ,  27.        ,   7.8958    ],
       [  1.        ,   0.        ,  64.        ,  26.        ],
       [  3.        ,   0.        ,  35.        ,   7.125     ],
       [  1.        ,   1.        ,  19.        ,  91.0792    ],
       [  3.        ,   0.        ,  38.        ,   7.05      ],
       [  3.        ,   0.        ,  30.5       ,   8.05      ],
       [  3.        ,   0.        ,  25.        ,   7.775     ],
       [  2.        ,   1.        ,  40.        ,  39.        ],
       [  1.        ,   0.        ,  47.        ,  38.5       ],
       [  3.        ,   0.        ,  30.        ,   9.5       ],
       [  1.        ,   0.        ,  40.        ,  31.        ],
       [  1.        ,   1.        ,  29.69911765,  52.        ],
       [  3.        ,   0.        ,  20.5       ,   7.25      ],
       [  1.        ,   1.        ,  29.69911765,  89.1042    ],
       [  1.        ,   0.        ,  36.        ,  26.2875    ],
       [  1.        ,   0.        ,  29.69911765, 221.7792    ],
       [  3.        ,   0.        ,  20.        ,   9.8458    ],
       [  1.        ,   0.        ,  71.        ,  34.6542    ],
       [  2.        ,   0.        ,  36.        ,  12.875     ],
       [  2.        ,   1.        ,  22.        ,  29.        ],
       [  3.        ,   1.        ,  48.        ,  34.375     ],
       [  2.        ,   0.        ,  23.        ,  11.5       ],
       [  1.        ,   1.        ,  32.        ,  76.2917    ],
       [  1.        ,   1.        ,  63.        ,  77.9583    ],
       [  2.        ,   0.        ,   0.83      ,  29.        ],
       [  3.        ,   0.        ,  25.        ,   7.25      ],
       [  1.        ,   0.        ,  35.        ,  26.55      ],
       [  1.        ,   1.        ,  49.        ,  25.9292    ],
       [  1.        ,   0.        ,  24.        ,  79.2       ],
       [  3.        ,   1.        ,  29.69911765,  14.4583    ],
       [  3.        ,   0.        ,  21.        ,   8.05      ],
       [  3.        ,   1.        ,  29.69911765,   7.8792    ],
       [  3.        ,   0.        ,  29.69911765,  15.2458    ],
       [  2.        ,   0.        ,  29.69911765,   0.        ],
       [  3.        ,   1.        ,   5.        ,  12.475     ],
       [  1.        ,   0.        ,  49.        ,  56.9292    ],
       [  3.        ,   1.        ,  15.        ,  14.4542    ],
       [  1.        ,   1.        ,  29.69911765, 110.8833    ],
       [  3.        ,   0.        ,  29.        ,   7.775     ],
       [  3.        ,   0.        ,  42.        ,   7.55      ],
       [  3.        ,   1.        ,  18.        ,  17.8       ],
       [  3.        ,   0.        ,  21.        ,   8.4333    ],
       [  2.        ,   1.        ,  44.        ,  26.        ],
       [  2.        ,   0.        ,  28.        ,  13.        ],
       [  2.        ,   0.        ,  37.        ,  26.        ],
       [  3.        ,   1.        ,  39.        ,  29.125     ],
       [  2.        ,   1.        ,  34.        ,  32.5       ],
       [  2.        ,   0.        ,  30.        ,  13.        ],
       [  2.        ,   0.        ,  66.        ,  10.5       ],
       [  1.        ,   1.        ,  29.69911765, 146.5208    ],
       [  3.        ,   0.        ,  43.        ,   8.05      ],
       [  3.        ,   0.        ,  29.69911765,   8.7125    ],
       [  3.        ,   0.        ,  24.        ,   7.4958    ],
       [  3.        ,   0.        ,  18.        ,   7.7958    ],
       [  3.        ,   1.        ,  29.69911765,  24.15      ],
       [  3.        ,   0.        ,  29.69911765,   8.05      ],
       [  3.        ,   0.        ,  29.69911765,   7.05      ],
       [  3.        ,   0.        ,  29.69911765,  56.4958    ],
       [  3.        ,   1.        ,  29.69911765,   7.7875    ],
       [  2.        ,   1.        ,  36.        ,  26.        ],
       [  3.        ,   1.        ,  32.        ,  15.5       ],
       [  3.        ,   0.        ,  23.5       ,   7.2292    ],
       [  1.        ,   0.        ,  29.69911765,  26.55      ],
       [  2.        ,   0.        ,  39.        ,  13.        ],
       [  1.        ,   1.        ,  29.69911765,  82.1708    ],
       [  3.        ,   0.        ,  29.69911765,   8.4583    ],
       [  1.        ,   0.        ,  65.        ,  61.9792    ],
       [  2.        ,   0.        ,  23.        ,  10.5       ],
       [  1.        ,   1.        ,  29.69911765,  51.8625    ],
       [  3.        ,   0.        ,  22.        ,   7.8958    ],
       [  3.        ,   0.        ,  35.        ,   7.05      ],
       [  1.        ,   0.        ,  23.        ,  63.3583    ],
       [  2.        ,   1.        ,  18.        ,  13.        ],
       [  1.        ,   0.        ,  36.        ,  26.3875    ],
       [  3.        ,   1.        ,   9.        ,  15.2458    ],
       [  3.        ,   0.        ,  17.        ,   7.125     ],
       [  3.        ,   0.        ,  29.69911765,   7.225     ],
       [  3.        ,   1.        ,  38.        ,  31.3875    ],
       [  2.        ,   1.        ,  17.        ,  10.5       ],
       [  3.        ,   1.        ,   4.        ,  16.7       ]])

In [34]:
# Step 7: Make Predictions and Evaluate

# Predict on test set
y_pred = nb_model.predict(X_test)

# Evaluation metrics
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("✅ Accuracy:", accuracy_score(y_test, y_pred))
print("\n📊 Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\n📋 Classification Report:\n", classification_report(y_test, y_pred))

✅ Accuracy: 0.7597765363128491

📊 Confusion Matrix:
 [[83 22]
 [21 53]]

📋 Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.79      0.79       105
           1       0.71      0.72      0.71        74

    accuracy                           0.76       179
   macro avg       0.75      0.75      0.75       179
weighted avg       0.76      0.76      0.76       179

In [35]:
# "Out of 179 total predictions, around 76% were correct.
# That’s a decent accuracy, especially for a simple probabilistic model like Naive Bayes."